# Generated by Django 5.2.9 on 2026-01-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_actor_director_movie_description_movie_overview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('movies', models.ManyToManyField(related_name='tags', to='movies.movie')),
            ],
        ),
    ]
