# Generated by Django 5.2.9 on 2026-01-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_actors_remove_tag_movies_movie_cast_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
