# Generated by Django 5.2.9 on 2026-01-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_delete_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cast',
            new_name='actors',
        ),
    ]
